name: Run script and add output as comment
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  run-script-add-output-comment:
    name: Run script and add output as comment
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        bash yolo.sh > yolo.sh.output
        output="$(cat yolo.sh.output)"
        output="${output//$'\n'/\\n}"
        output="${output// /â€‚}"     # replace regular space with 'En Space'
        echo "::set-output name=run-bash-script::$output"
      id: run_script
    - uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = '${{ steps.run_script.outputs.run-bash-script }}'
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
